name: Python application

# Activar el flujo de trabajo solo cuando haya un push o pull request
on:
  push:
    branches:
      - main  # Puede ser la rama principal de tu repositorio
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliza el sistema operativo más reciente de Ubuntu

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  # Esta acción obtiene el código del repositorio

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # La versión de Python que usarás en el proyecto

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias de tu proyecto si las tienes en un archivo requirements.txt

    - name: Run Python code
      run: |
        python main.py  # Asegúrate de que 'main.py' sea el archivo principal donde resides el código

    - name: Upload results (optional)
      if: success()  # Si el script se ejecutó correctamente
      run: |
        echo "Python code executed successfully"
